# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-05 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='breakdownofbill',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='patientbill',
            name='invoiceid',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
