# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_auto_20180506_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbill',
            old_name='breakdownofbill',
            new_name='breakdownbill',
        ),
    ]
