# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-06 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_auto_20180506_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientbill',
            old_name='breakdownbill',
            new_name='billbreakdown',
        ),
    ]
