# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20180130_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='i03_menopausal_screen',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labs',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='lab_name'),
        ),
    ]
