# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_auto_20180206_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresults',
            name='tests_done',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='tests_done',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
