# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20180206_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresults',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/lab/'),
        ),
        migrations.AlterField(
            model_name='radiologyresult',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/radiology/'),
        ),
    ]
