# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0004_auto_20180206_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresults',
            name='id',
        ),
        migrations.RemoveField(
            model_name='labs',
            name='id',
        ),
        migrations.RemoveField(
            model_name='radiology',
            name='id',
        ),
        migrations.RemoveField(
            model_name='radiologyresult',
            name='id',
        ),
        migrations.AddField(
            model_name='labresults',
            name='labresult_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='labresults',
            name='triage_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='lab_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='labs',
            name='triage_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='radiology',
            name='radiology_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='radiology',
            name='triage',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='radiologyresult_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='radiologyresult',
            name='triage_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
