# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0005_auto_20180213_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labs',
            name='lab_id',
        ),
        migrations.RemoveField(
            model_name='radiology',
            name='triage',
        ),
        migrations.AddField(
            model_name='labs',
            name='id',
            field=models.AutoField(auto_created=True, default=324434, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiology',
            name='triage_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radiology',
            name='radiology_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
