# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0006_auto_20180213_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiology',
            name='radiology_id',
        ),
        migrations.AddField(
            model_name='radiology',
            name='id',
            field=models.AutoField(auto_created=True, default=1242134334, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
