# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_patientvisit_diag_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testsresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('resulturl', models.CharField(blank=True, max_length=255)),
                ('uploaded_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
