# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_testsresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='current_diagnosis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
