# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=30)),
                ('visit_id', models.CharField(max_length=30)),
                ('radiology_no', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, max_length=200, null=True)),
                ('diagnosis', models.TextField(blank=True, max_length=100, null=True)),
                ('prescription_id', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.IntegerField(max_length=2)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
