# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='examination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='his_presenting_illness',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='plan_of_managemnt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='query_diagnosis',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
