# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='status',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
