# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientvisit',
            name='id',
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),

        ),
    ]
