# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_auto_20180211_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvisit',
            name='id',
            field=models.AutoField(auto_created=True, default=12345, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
