# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_auto_20180211_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvisit',
            old_name='visit_i',
            new_name='visit_id',
        ),
    ]
