# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-14 09:33
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_auto_20180214_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientvisit',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='patient_no'),
        ),
    ]
