# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-02 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='patient_no')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('oxygen_saturation', models.FloatField()),
                ('urinalysis', models.TextField(blank=True, max_length=400, null=True)),
                ('heart_rate', models.CharField(max_length=100)),
                ('others', models.TextField(blank=True, max_length=200, null=True)),
                ('attending_nurse', models.CharField(blank=True, max_length=30, null=True)),
                ('patient_no', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ('last_updated',),
            },
        ),
    ]
