# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='height',
            field=models.CharField(default='nil', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='models',
            name='random_glucose',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='models',
            name='weight',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
