# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='attending_nurse',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='others',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='patient_id'),
        ),
        migrations.AlterField(
            model_name='models',
            name='urinalysis',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
