# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_auto_20180130_1115'),
        ('nurse', '0002_auto_20180130_0936'),
    ]

    operations = [
    ]
