# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_auto_20180206_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'ordering': ('-last_updated',)},
        ),
    ]
