# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 10:51
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_merge_20180130_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='patient_id'),
        ),
    ]
