# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_auto_20180211_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='id',
        ),
        migrations.AddField(
            model_name='models',
            name='triage_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
