# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-14 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0003_auto_20180213_0855'),
        ('nurse', '0004_auto_20180211_2013'),
    ]

    operations = [
    ]
