# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='signature',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
