# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-13 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0002_auto_20180204_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDawa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=300)),
                ('price', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ('brand',),
            },
        ),
    ]
