# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_auto_20180211_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='prescription_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
