# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-11 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0004_auto_20180211_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='prescription_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
