# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0005_auto_20180211_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='email',
            field=models.CharField(default='ss@g.l', max_length=50),
            preserve_default=False,
        ),
    ]
