# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0006_models_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
