# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0007_auto_20180212_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
