# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-13 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0008_auto_20180213_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='triage_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
