# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-14 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_mydawa'),
        ('medication', '0009_models_triage_id'),
    ]

    operations = [
    ]
