# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=30)),
                ('street_name', models.CharField(max_length=30)),
                ('apartment_name', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('postal_address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('next_of_kin', models.TextField(max_length=100)),
                ('n_of_kin_rel', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('primary_insurance', models.TextField(max_length=100)),
                ('secondary_insurance', models.TextField(max_length=100)),
                ('pri_ins_sub', models.BooleanField(max_length=100)),
                ('sec_ins_sub', models.BooleanField()),
                ('other_ins_subscriber', models.TextField(max_length=100)),
                ('subscriber_relationship', models.TextField(max_length=100)),
                ('sub_address', models.TextField(max_length=100)),
                ('ss_number', models.TextField(max_length=100)),
                ('sub_ss_number', models.TextField(max_length=100)),
                ('alt_phone', models.IntegerField()),
                ('sub_work_phone', models.TextField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sub_dob', models.DateField(blank=True, null=True)),
                ('sub_employer', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
