# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='fam_hist',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='social_hist',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
