# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20180129_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='models',
            name='id',
        ),
        migrations.AlterField(
            model_name='models',
            name='patient_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
