# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_merge_20180223_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='session_id',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
