# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180129_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='sub_work_phone',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
