# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180224_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergies',
            options={'verbose_name': 'Allergy', 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'County', 'verbose_name_plural': 'Counties'},
        ),
        migrations.RenameField(
            model_name='county',
            old_name='County',
            new_name='county',
        ),
    ]
