# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180205_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('patient_no', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments')),
            ],
        ),
        migrations.AddField(
            model_name='models',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
