# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180129_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='alcohol_frequency',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='alergies',
            field=models.TextField(blank='True', max_length=1000, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='alocohol_type',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='caffein_daily_amt',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='childrens',
            field=models.CharField(blank='True', max_length=100, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='cigar_per_day',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='dexa',
            field=models.TextField(blank='True', max_length=100, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='drug_type',
            field=models.TextField(blank='True', max_length=100, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='exercise_freq',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='genetic_diseases',
            field=models.TextField(blank='True', max_length=1000, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='have_will',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_chew_tobacco',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_drink_alcohol',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_drug_used',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_exercise',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_lost_interest',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_quit_before',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_smoker',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_special_diet',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='if_use_caffein',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='is_sadder',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='last_blood_work',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='last_colonoscopy',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='last_mammogram',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='last_menstrual',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='last_pap_smear',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='last_phys_examination',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='last_tetanus_shot',
            field=models.DateField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='living_children',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='marital_status',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='medical_information',
            field=models.TextField(blank='True', max_length=1000, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='methods_of_contraception',
            field=models.TextField(blank='True', max_length=100, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='miscourages',
            field=models.TextField(blank='True', max_length=100, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='no_children',
            field=models.IntegerField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='no_of_yr_smoking',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='no_pregnancies',
            field=models.IntegerField(blank='True', null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='occupation',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='preferred_pharmacy',
            field=models.TextField(blank='True', max_length=100, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='prev_docs',
            field=models.CharField(blank='True', max_length=200, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='special_diet',
            field=models.TextField(blank='True', max_length=100, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='spouse',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='surgeries',
            field=models.TextField(blank='True', max_length=1000, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='tobacco_quit_duration',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='when_drug_used',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='models',
            name='yrs_chewing_tobacco',
            field=models.CharField(blank='True', max_length=30, null='True'),
        ),
    ]
