# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180206_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
