# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-26 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180226_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='county',
            new_name='county_name',
        ),
    ]
