# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20180226_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=300)),
            ],
        ),
    ]
