# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_insurancecompanies_medicationhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={},
        ),
        migrations.RenameField(
            model_name='county',
            old_name='county_name',
            new_name='County',
        ),
    ]
