# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-06 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20180206_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='media/users/'),
        ),
    ]
