# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-13 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_auto_20180206_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
