# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-13 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_models_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='session_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
