# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-21 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20180213_1320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='models',
            new_name='Patient',
        ),
        migrations.AlterField(
            model_name='children',
            name='patient_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, to_field='patient_no', verbose_name='patient_no'),
        ),
    ]
