# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pre_authorization',
            name='id',
        ),
        migrations.AlterField(
            model_name='pre_authorization',
            name='code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
