# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20180125_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_benefits',
            name='member_no',
            field=models.CharField(max_length=20),
        ),
    ]
