# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 17:24
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180125_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_acceptance',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='member_no'),
        ),
        migrations.AlterField(
            model_name='member_anniversary',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='member_no'),
        ),
        migrations.AlterField(
            model_name='member_benefits',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='member_no'),
        ),
        migrations.AlterField(
            model_name='pre_authorization',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='member_no'),
        ),
    ]
