# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20180130_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_authorization',
            name='provider',
            field=models.IntegerField(choices=[(0, 'AAR'), (1, 'ACE'), (2, 'Sanlam'), (3, '21st centuary')], default=0),
        ),
    ]
