# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20180130_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_authorization',
            name='authority_type',
            field=models.IntegerField(choices=[(0, 'In Patient'), (1, 'Out Patient'), (3, 'Dental'), (4, 'Maternity')], default=0),
        ),
    ]
