# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20180130_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_authorization',
            name='provider',
            field=models.IntegerField(choices=[(0, 'AGA KHAN HOSPITAL NAIROBI'), (1, 'NAIROBI HOSPITAL'), (2, 'KENYATTA HOSPITAL'), (3, 'KAREN HOSPITAL')], default=0),
        ),
    ]
