# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20180130_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_authorization',
            name='anniv',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='pre_authorization',
            name='ward',
            field=models.IntegerField(choices=[(0, 'General Ward'), (1, 'Maternity Ward'), (2, 'Children Ward'), (3, 'Critical Ward')], default=0),
        ),
    ]
