# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_auto_20180130_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_authorization',
            name='anniv',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
