# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20180130_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_authorization',
            name='anniv',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
