# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 06:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20180130_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_benefits',
            name='suspended_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
