# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 06:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_member_benefits_suspended_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_benefits',
            name='suspended_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
