# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20180131_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_authorization',
            name='internal_notes',
            field=models.CharField(choices=[('EXT', 'Ext'), ('NEW', 'New')], default='NEW', max_length=100),
        ),
    ]
