# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_pre_authorization_internal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_authorization',
            name='admit_days',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='pre_authorization',
            name='date_admitted',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='pre_authorization',
            name='day_bed_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
