# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-31 10:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20180131_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_benefits',
            name='suspended_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
